services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    networks:
      - app-network

  backend:
    build: 
      context: ./server
    container_name: extradetailer_backend
    env_file:
      - ./server/.env
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: 
      context: ./client
    container_name: extradetailer_frontend
    env_file:
      - ./client/.env
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: extradetailer_nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./nginx/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - ./nginx/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./nginx/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - ./nginx/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
    depends_on:
      - nginx
    networks:
      - app-network
    command: certonly --webroot --webroot-path=/var/www/certbot --email your-email@example.com --agree-tos --no-eff-email --force-renewal -d extradetailers.com -d www.extradetailers.com
    
volumes:
  pgdata:

networks:
  app-network:
    driver: bridge