name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd ${{ secrets.DEPLOY_DIR }}
            git pull origin master
            
            # Stop existing containers
            sudo docker compose down
            
            # First run - start everything except certbot
            sudo docker compose up -d --build db backend frontend nginx
            
            # Wait for nginx to be ready
            sleep 10
            
            # Run certbot to get initial certificates
            sudo docker compose run --rm certbot
            
            # Restart nginx with SSL config
            sudo docker compose restart nginx
            
            # Start everything normally
            sudo docker compose up -d
          EOF
